### ISSUE TITLE
All products including postgresql use pgAdmin uniformly and modify related documents

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-postgresql#3]
**What type of your feature request?**  

- [ ] Add new features
- [ ] Improve current features

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by qiaofeng1227** [comment]
phppgadmin：
ansible-awx
ansible-canvas

pgadmin：
ansible-superset
ansible-odoo
ansible-postgresql
